# Generated by Django 6.0 on 2025-12-27 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('country', models.CharField(max_length=5)),
                ('device_id', models.CharField(max_length=20)),
                ('account_age_days', models.IntegerField()),
                ('risk_score', models.IntegerField()),
                ('fraud_flag', models.BooleanField()),
                ('explanation', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
