# Generated by Django 6.0 on 2025-12-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='device_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
    ]
