# Generated by Django 6.0 on 2025-12-27 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_transaction_amount_alter_transaction_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_age_days',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='device_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_score',
            field=models.IntegerField(),
        ),
    ]
