# Generated by Django 6.0 on 2025-12-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_transaction_account_age_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.CharField(default=1, help_text='Sender account / customer ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
