# Generated by Django 6.0 on 2025-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_transaction_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_flag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='risk_score',
            field=models.IntegerField(),
        ),
    ]
